### ISSUE TITLE
진행하면서, 겪은 에러&배운 점

### ISSUE THREAD

**Issue by marioahn** [marioahn/node.postmall.LV2#1]
### 1. Issue들
(0)dotenv이용해서, secret key도 숨겨 줄 수 있음을 알게 되었고, 적용하였다
(1)API들의 에러 처리에 관해
(2)게시글 조회API에서 userId, postId 둘 다 나오는데 이걸 헷갈려서 코드를 잘못 짰었다
(3)게시글 수정API를 thunder client에서 보낼 때, 토큰값을 입력 안하고 body탭에서 content만 입력해도 작동이 된다
(4)게시글 수정API를 작성할 때, findOne 대신 find를 사용했고, id가 다른 경우 게시글 수정권한이 없는 에러를 맨 위에 둠으로 인해 발생하는 오류상황
(5)API의 에러처리를 할 때
(6)virtual settings 정리

### 2. 위 이슈들의 내용이 많아, 노션에 작성한 링크에 대신 작성하였다
- https://marioa.notion.site/082f861147a64a7494852f78d4563089?pvs=4

**Comment by ohbin-kwon** [comment]
4. 콘솔을 찍어보시고 디버깅해보신 부분이 감명깊었습니다. 의식의 흐름대로 적어주셨는데 아주 좋은 에러해결과정이네요. 앞으로도 문제해결하실때 이런 흐름대로 해결하시고, 문제를 어떻게 해결했는지 포인팅아웃 해주시면 좋을것같습니다!!! findOne과 find의 차이점을 아주 잘 파악해가고 계신것같습니다.

**Comment by marioahn** [comment]
피드백 감사합니다!
- client툴에서 쿠키를 한번 심게되면, 그것을 지우지 않는 이상(ex: clear all cookies) 보유한 상태에서 api요청마다 토큰을 자동으로 보내서 인증을 client툴 안에서 바로바로 완료한다는 점 잘 이해했습니다
- 기술매니저님이 콘솔 로그 찍으면서 에러를 해결하는 과정을 잘 알려주셔서 혼자서도 수월히 에러를 처리할 수 있었습니다 감사합니다!
